### ISSUE TITLE
Invalid include in cpp file.

### ISSUE THREAD

**Issue by SealTV** [vizor-games/infraworld-cornerstone#3]
In .cpp file first include must be .h file with same name as .cpp file.

**Comment by RChehowski** [comment]
Hello @SealTV. This is only valid if `PCHUsage != ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs` in your `ModuleNameBuild.cs`. Since this is not a required option, the converter always passes precompiled header if `precompiled_header` is not set in your config. You may set it to empty string or simply comment it out to achieve required behavior. Please double-check this, I am considering it not an issue at this time. Best regards.
