### ISSUE TITLE
Errors with UE4.20 on windows

### ISSUE THREAD

**Issue by 0xmono** [vizor-games/infraworld-cornerstone#4]
Warning C4668 whould be disabled before includes of grpc headers or it causes following error:
`port_platform.h(398): error C4668: 'GPR_FORBID_UNREACHABLE_CODE' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'`

**Comment by RChehowski** [comment]
Hi there! Thank you for reporting an issue. This issue is mostly related to the [runtime](https://github.com/vizor-games/InfraworldRuntime), not the converter utility. We do not currently supporting UE4.20+. It seems to be just a warning, threatened as an error by a newer engine versions. What you can try is to disable such a warning for your target project. I'll try to investigate an error a bit later and then post an answer into this thread. Wish you best of luck.

**Comment by nikomoravec** [comment]
fixed in [8300289](https://github.com/vizor-games/infraworld-cornerstone/commit/83002895bb5dc4386e268f848230262b6d23303f)
